#ifndef XBOX_H
#define XBOX_H

#define TITLE_ID_S           "43540001"
#define USER_DATA_PATH       "E:\\UDATA"
#define USER_DATA_TITLE_PATH USER_DATA_PATH "\\" TITLE_ID_S
#define USER_DATA_SAVE_PATH  USER_DATA_TITLE_PATH "\\" "000000000000"

#endif
